name: Project 5 - CD
on: 
    push:
        branches:
            - 'main'
    release:
        types: [published]
env:
    DOCKER_HUB_REPO: loberry/project4_repo
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up DOcker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    repository: loberry/project4_repo
                    tag_with_ref: true
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: user/app:latest
